### PR TITLE
docs: correct default cache path

### LINKED ISSUE #645: support: the default cachedir seems incorrect without `actions/setup-go` step
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I noticed that my workflow always say there is no Hugo modules cached found. And I create a testing repo for checking the path of `cachedir`, it's different (`/tmp/hugo_cache_runner/`) with the one (`/home/runner/.cache/hugo_cache`) on README.

### Relevant links

```markdown
Public repository: https://github.com/razonyang/github-workflows-testing
YAML config: 
YAML workflow: https://github.com/razonyang/github-workflows-testing/blob/main/.github/workflows/hugo-modules-caching.yml
```

### Relevant log output

image

### Additional context.

Full logs are available on https://github.com/razonyang/github-workflows-testing/actions/runs/8252748983/job/22573007579.

### PR DESCRIPTION
**Pull request by razonyang**
May fixes #645, but I'm not sure, since I didn't find any information about this cache path after searching docs, @deining would you mind checking if this PR is OK?

### CODE REVIEW

**Comment by deining** [comment]
> @deining would you mind checking if this PR is OK?

I suspect it makes a difference whether your workflow contains `actions/go` or not. If `actions/go` is part of the workflow, the cachedir is `/home/runner/.cache/hugo_cache`, without `actions/go` the cachedir is `/tmp/hugo_cache_runner`.
I created this [PR](https://github.com/razonyang/github-workflows-testing/pull/1) to confirm. @razonyang: Can you please approve this PR and check the results of the workflow run? Thanks!

**Comment by razonyang** [comment]
@deining You're right, I modified the PR a little more to cover those two use cases.

**Comment by Zer0xxxx** [comment]
Hello @razonyang !
We've discussed yesterday on the Hugo's forum about this.
https://discourse.gohugo.io/t/how-to-cache-hugo-modules-in-a-github-action/50334

I'm reaching you because I've also pushed a PR on this repo, trying to fix this with an another approach.
- https://github.com/peaceiris/actions-hugo/pull/650

What are your thoughts?
Warm regards.

**Comment by Zer0xxxx** [comment]
> @Zer0xxxx GitHub actions can be ran on Windows, there is no `/tmp/` on Windows, so I'd recommend leaving a separate section/paragraph about this approach, rather than deleting previous appraoches, but I'm not maintainer of this repo, you can wait for maintainer to check and reply.

Oh, you're right. I'm dumb, haha!

I don't think this is necessarily a problem, though, since I've specified in the documentation snippets that the action runs on Ubuntu-22.04 (just above the `env` section).

Documenting absolutely every conceivable use seems to me to be rather complicated, and confusing.

Are there any use cases that I might miss where launching the action in a workflow on Windows is better than on Ubuntu?

**Comment by razonyang** [comment]
> Are there any use cases that I might miss where launching the action in a workflow on Windows is better than on Ubuntu?

Maybe tests purpose, to make sure the theme works on all supported platforms (Linux, macOS and Windows).

**Comment by Zer0xxxx** [comment]
> > Are there any use cases that I might miss where launching the action in a workflow on Windows is better than on Ubuntu?
> 
> Maybe tests purpose, to make sure the theme works on all supported platforms (Linux, macOS and Windows).

Hmm... Using a _matrix_, then?
Interesting, I might have a look. I _think_ it is possible to define separate env variables depending on the _matrix_ context.

**Comment by peaceiris** [comment]
👀

**Comment by Zer0xxxx** [comment]
> 👀

Should I nail it too? 😉

**Comment by razonyang** [comment]
Lack of time to resolve conflicts, and env approach is not bad, closing this for now.

**Pull request closed without merging**
